name: Build docker image

on: 
  push: 
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request: 
    branches: [ "master" ]

env:
  PA_TOKEN: ${{ secrets.PA_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-php-8_3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: 8.3
          tags: 8.3,latest
          platform: linux/amd64,linux/arm64

  build-php-8_2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: ./.github/actions
        with:
          version: 8.2
          tags: 8.2
          platform: linux/amd64,linux/arm64